/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;


import Model.MahasiswaModel;
import Controller.RuanganController;
import Model.Mahasiswa;
import Model.Ruangan;
import Model.Session;
import Model.KoneksiDB;
import java.io.IOException;

import java.sql.Connection;
import javax.swing.JScrollPane;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wahyu
 */
public class Akun extends javax.swing.JPanel {
    private JScrollPane contentScrollPane;
    private final Connection connection;
    private final MahasiswaModel mahasiswaController;
    private final RuanganController ruanganController;
    private boolean isEditing = false;
    private int selectedRow = -1;
    
    /**
     * Creates new form akun
     * @param contentScrollPane
     */
    public Akun(JScrollPane contentScrollPane) {
        this.contentScrollPane = contentScrollPane;
        this.connection = KoneksiDB.getConnection(); // Koneksi ke database
        initComponents();
        mahasiswaController = new MahasiswaModel(this);
        ruanganController = new RuanganController();
        jLabelUser.setText("Logged in as: " + Session.getEmail());
        loadMahasiswaData();
        loadRuanganData();
    }
    
    private void loadMahasiswaData() {
        Mahasiswa mahasiswa = mahasiswaController.getCurrentMahasiswa();
        if (mahasiswa != null) {
            nimTextField.setText(mahasiswa.getNim());
            namaTextField.setText(mahasiswa.getNama());
            passwordField.setText(mahasiswa.getPassword());
            setFieldsEditable(false);
        }
    }
    private void loadRuanganData() {
        int mahasiswaId = mahasiswaController.getCurrentMahasiswa().getId();
        List<Ruangan> ruanganList = ruanganController.getRuanganByMahasiswaId(mahasiswaId);

        DefaultTableModel model = (DefaultTableModel) tableRuangan.getModel();
        model.setRowCount(0); // Clear existing data

        for (Ruangan ruangan : ruanganList) {
            Object[] row = {
                ruangan.getRuang(),
                ruangan.getTanggal(),
                ruangan.getSesi1(),
                ruangan.getSesi2(),
                ruangan.getSesi3(),
                ruangan.getSesi4()
            };
            model.addRow(row);
        }
    }
    private void setFieldsEditable(boolean editable) {
        nimTextField.setEditable(editable);
        namaTextField.setEditable(editable);
        passwordField.setEditable(editable);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        nimTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRuangan = new javax.swing.JTable();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        exportButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Akun");

        jLabelUser.setText("Akun");

        nimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("NIM");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nama");

        namaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Password");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("List Ruangan");

        tableRuangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ruang", "Tanggal", "Sesi 1", "Sesi 2", "Sesi 3", "Sesi 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableRuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRuanganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableRuangan);
        if (tableRuangan.getColumnModel().getColumnCount() > 0) {
            tableRuangan.getColumnModel().getColumn(0).setHeaderValue("Ruang");
            tableRuangan.getColumnModel().getColumn(1).setHeaderValue("Tanggal");
            tableRuangan.getColumnModel().getColumn(2).setHeaderValue("Sesi 1");
            tableRuangan.getColumnModel().getColumn(3).setHeaderValue("Sesi 2");
            tableRuangan.getColumnModel().getColumn(4).setHeaderValue("Sesi 3");
            tableRuangan.getColumnModel().getColumn(5).setHeaderValue("Sesi 4");
        }

        editButton.setText("Edit Profile");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Hapus Pinjaman");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        exportButton.setText("Export Bukti");
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelUser)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 383, Short.MAX_VALUE)
                                .addComponent(exportButton)
                                .addGap(18, 18, 18)
                                .addComponent(deleteButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(editButton)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3)
                                            .addComponent(nimTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                            .addComponent(jLabel4)
                                            .addComponent(namaTextField)
                                            .addComponent(jLabel5)
                                            .addComponent(passwordField))
                                        .addGap(29, 29, 29)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE))))
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabelUser))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(exportButton))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimTextFieldActionPerformed

    private void namaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        if (isEditing) {
            int response = JOptionPane.showConfirmDialog(this, "Do you want to save changes?", "Confirm", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                Mahasiswa mahasiswa = new Mahasiswa(
                    0, // id is not needed for update
                    Session.getEmail(),
                    nimTextField.getText(),
                    namaTextField.getText(),
                    new String(passwordField.getPassword())
                );
                boolean updated = mahasiswaController.updateMahasiswa(mahasiswa);
                if (updated) {
                    JOptionPane.showMessageDialog(this, "User updated successfully.");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to update user.");
                }
            }
            setFieldsEditable(false);
            editButton.setText("Edit");
        } else {
            setFieldsEditable(true);
            editButton.setText("Save");
        }
        isEditing = !isEditing;
    }//GEN-LAST:event_editButtonActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableRuangan.getSelectedRow();
    if (selectedRow != -1) {
        // Dapatkan data dari tabel
        String ruang = tableRuangan.getValueAt(selectedRow, 0).toString();
        String tanggal = tableRuangan.getValueAt(selectedRow, 1).toString();
        String sesi1 = tableRuangan.getValueAt(selectedRow, 2).toString();
        String sesi2 = tableRuangan.getValueAt(selectedRow, 3).toString();
        String sesi3 = tableRuangan.getValueAt(selectedRow, 4).toString();
        String sesi4 = tableRuangan.getValueAt(selectedRow, 5).toString();

        // Buat instance RuanganController
        RuanganController ruanganController = new RuanganController();

            try {
                // Panggil method untuk ekspor PDF
                ruanganController.exportToPdf(ruang, tanggal, sesi1, sesi2, sesi3, sesi4);
            } catch (IOException ex) {
                Logger.getLogger(Akun.class.getName()).log(Level.SEVERE, null, ex);
            }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih satu baris terlebih dahulu.", "Warning", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_exportButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        if (selectedRow != -1) {
            int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this entry?", "Confirm", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                DefaultTableModel model = (DefaultTableModel) tableRuangan.getModel();
                String ruang = (String) model.getValueAt(selectedRow, 0);
                java.sql.Date tanggal = (java.sql.Date) model.getValueAt(selectedRow, 1);

                boolean deleted = ruanganController.deleteRuangan(ruang, tanggal);
                if (deleted) {
                    model.removeRow(selectedRow);
                    JOptionPane.showMessageDialog(this, "Entry deleted successfully.");
                    selectedRow = -1; // Reset selected row
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to delete entry.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row first.");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void tableRuanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRuanganMouseClicked
        // TODO add your handling code here:
        selectedRow = tableRuangan.getSelectedRow();
    }//GEN-LAST:event_tableRuanganMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton exportButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTable tableRuangan;
    // End of variables declaration//GEN-END:variables
}
