/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author Wahyu
 */
import javax.swing.*;

public class Welcome extends javax.swing.JPanel {
    private JScrollPane contentScrollPane;

    /**
     * Creates new form welcome
     * @param contentScrollPane
     */
    public Welcome(JScrollPane contentScrollPane) {
        this.contentScrollPane = contentScrollPane;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mulaiButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(138, 43, 226));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 54)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selamat Datang");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 37, 680, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Peminjaman Ruangan STIS");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 680, 50));

        mulaiButton.setBackground(new java.awt.Color(153, 153, 255));
        mulaiButton.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mulaiButton.setForeground(new java.awt.Color(0, 51, 51));
        mulaiButton.setText("Mulai");
        mulaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiButtonActionPerformed(evt);
            }
        });
        add(mulaiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 150, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Welcome.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 680, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void mulaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiButtonActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new Login(contentScrollPane));
    }//GEN-LAST:event_mulaiButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton mulaiButton;
    // End of variables declaration//GEN-END:variables
}
